### ISSUE TITLE
update to blender 2.8x required

### ISSUE THREAD

**Issue by aum7** [bastianilso/blender-csv-importer#1]
hi,

thanks for sharing this addon.

just installed latest fresh blender 2.8a, and following instruction for installation of this addon, i get
'upgrade to 2.8x required' notification.
though, it seems it is enabled. must check if it does work.

best regards,

simon
s love nia

**Comment by aum7** [comment]
hi,
i checked the addon, including restarting blender.
the importer is enabled, but 
it does not work as expected:
there is no 'file/import/Statistical Data (.csv)' option.

best regards,

have fun,

simon
s love nia


![2 8a blender-csv-importer - addon enabled](https://user-images.githubusercontent.com/9611505/74100458-795e7100-4b2f-11ea-9fa3-7d5a4f38725e.png)
![2 8a blender-csv-importer - no import csv](https://user-images.githubusercontent.com/9611505/74100459-7a8f9e00-4b2f-11ea-8da8-592fde0fd4b9.png)

**Comment by aum7** [comment]
hi,
i have spent some time trying to update to blender 2.8, and all the 'necessary' changes that i could trace with uncle google, are implemented in attached file.

though, it does not work properly. and i am unable to find the cause of error.

hopefully this will be updated properly, by someone who knows how.

best regard,

s love nia

[blender-csv-importer-chistabo.zip](https://github.com/bastianilso/blender-csv-importer/files/4177064/blender-csv-importer-chistabo.zip)

**Comment by bastianilso** [comment]
Hi @Chistabo thanks a lot for the notice and for your help addressing this! I sat down for 1 hour today and implemented your changes and a few others that should ensure that all current supported visualization types can execute without problems. So the CSV Importer should now support Blender 2.80 since 7b69aa86a1093b6d2391662204f57b8e83390403.

There were a few API changes that I am still awaiting answers on from the Blender community, such as [Font's can only have scale applied](https://blender.stackexchange.com/questions/166399/for-blender-2-80-api-bpy-ops-objects-transform-yields-runtimeerror-fonts-can-o) and the [constraint_orientation parameter in bpy.ops.transform](https://blender.stackexchange.com/questions/166397/for-blender-2-80-api-what-replaces-the-constraint-orientation-parameter-in-bpy). Once they have been addressed, the visualizations should work just as well as they did in 2.79. But for the most part the plug-in should be usable again in Blender 2.8.x

**Comment by aum7** [comment]
hi,
thanks. will check it out.

godspeed,

s love nia

**Comment by bastianilso** [comment]
hi @Chistabo did it work out for you? I will close this issue, but in case you experience any troubles with the plugin in blender 2.8, just open a new issue. :+1:
